CREATE SCHEMA `chat` ;

CREATE TABLE USER (
  ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  CPF VARCHAR(20) NOT NULL,
  ROLE VARCHAR(10) NOT NULL
);


CREATE TABLE MESSAGE (
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TO INT  NOT NULL, 
    FROM INT NOT NULL, 
    DATE TIMESTAMP NOT NULL
);

